#!/bin/bash
# .git/hooks/post-checkout

# Check if upstream remote exists
if ! git remote | grep -q "^upstream$"; then
    echo "Adding upstream remote..."
    git remote add upstream https://github.com/peerigon/template.git
    echo "Upstream remote added successfully!"
fi

git remote set-url --push upstream DISABLED