name: 🧪 Test

on:
  push:
    branches:
      - main
      - beta
  pull_request: {}
  workflow_dispatch: {}

permissions: {}

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      actions: write
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/beta' }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main
        with:
          persist-credentials: false

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c # main
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: 🗄 Cache node_modules
        id: cache-node_modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # main
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: 🗄 Cache .eslintcache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # main
        with:
          path: .eslintcache
          key: eslintcache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: 🔍 Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts --prefer-offline --no-audit

      - name: 🧪 Run tests
        env:
          CI: true
        run: |
          npm test
